/// Flutter icons DSIcons
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  DSIcons
///      fonts:
///       - asset: fonts/DSIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

//ignore_for_file: constant_identifier_names
class DSIcons {
  DSIcons._();

  static const _kFontFam = 'DSIcons';
  static const String? _kFontPkg = null;

  static const IconData sword_filled = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sword = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData demon = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData demon_filled = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
